export default {
    angular: require('./angular.png'),
    chat: require('./chat.png'),
    django: require('./django.png'),
    filter: require('./filter.png'),
    html: require('./html.png'),
    home: require('./home.png'),
    js: require('./js.png'),
    progress: require('./progress.png'),
    react: require('./react.png'),
    user: require('./user.png'),
    chatGery: require('./chatGery.png'),
    dashboard: require('./dashboard.png'),
    beg: require('./beg.png'),
    bell: require('./bell.png'),
    doller: require('./doller.png'),
    save: require('./save.png'),
    shield: require('./shield.png'),
    favorite: require('./favorite.png'),
    stopwatch: require('./stopwatch.png'),
    search: require('./search.png'),
    share: require('./share.png'),
    shadow1: require('./shadow1.png'),
    shadow2: require('./shadow2.png'),
    clock: require('./clock.png'),
    nitin: require('./nitin.png'),
    pdf: require('./pdf.png')
}